#!/usr/bin/env python3
"""Fetch Lucide icons and assemble templates/_icons.html.j2.
Run once from the project root: python3 tools/fetch_lucide_icons.py
"""
import re, urllib.request, pathlib

LUCIDE_VERSION = "0.468.0"
BASE = f"https://raw.githubusercontent.com/lucide-icons/lucide/{LUCIDE_VERSION}/icons"

ICONS = [
    "list-ordered", "users", "user", "chart-pie", "leaf", "flag",
    "graduation-cap", "hourglass", "globe", "star", "pencil-line",
    "swords", "file-text", "flask-conical", "terminal", "chart-bar-big",
    "tag", "trophy", "church", "calendar", "map-pin", "house",
    "map", "dna", "gem", "wheat", "scroll", "search", "building-2",
]

_STRIP = re.compile(
    r'\s+(?:stroke-width|stroke-linecap|stroke-linejoin|fill)="[^"]*"'
)

symbols = []
for name in ICONS:
    url = f"{BASE}/{name}.svg"
    print(f"  fetching {name}…", end=" ", flush=True)
    with urllib.request.urlopen(url) as r:
        svg = r.read().decode()
    # Extract inner content between outer <svg> tags
    inner = re.sub(r'<svg[^>]*>', '', svg).replace('</svg>', '').strip()
    # Strip layout attrs the .icon CSS will handle via inheritance;
    # keep stroke="currentColor" so colour inherits through shadow tree
    inner = _STRIP.sub('', inner)
    symbols.append(
        f'  <symbol id="icon-{name}" viewBox="0 0 24 24">\n'
        f'    {inner}\n'
        f'  </symbol>'
    )
    print("ok")

output = (
    '{# Auto-generated by tools/fetch_lucide_icons.py — do not edit manually #}\n'
    '<svg style="display:none" aria-hidden="true" focusable="false">\n'
    + '\n'.join(symbols)
    + '\n</svg>\n'
)
pathlib.Path("templates/_icons.html.j2").write_text(output)
print(f"\nWritten templates/_icons.html.j2 ({len(ICONS)} icons)")
