"""Second curation batch: ~500-name tail of the frequency distribution.
Covers plural/singular variants missed in batch 1, additional persons,
place references, and new category types.

Usage:
  python3 tools/seed_batch2.py [--dry-run]
"""
import csv, sys, subprocess
from pathlib import Path

OUT = Path("data/curation/classified_batch2.csv")

NATURE = [
    # trees — singular/plural variants + new species
    ("ciresului",       "Cireșului",      "tree"),
    ("marului",         "Mărului",        "tree"),
    ("castanilor",      "Castanilor",     "tree"),
    ("trandafirului",   "Trandafirului",  "flower"),  # singular of trandafirilor
    ("crinilor",        "Crinilor",       "flower"),
    ("ghiocelului",     "Ghiocelului",    "flower"),
    ("bujorilor",       "Bujorilor",      "flower"),
    ("lamaitei",        "Lămâiței",       "tree"),
    ("ulmilor",         "Ulmilor",        "tree"),
    ("macesilor",       "Măcesilor",      "tree"),
    ("smochinului",     "Smochinului",    "tree"),
    ("corcodusului",    "Corcodușului",   "tree"),
    ("maslinului",      "Măslinului",     "tree"),
    ("mestecenilor",    "Mestecenilor",   "tree"),
    ("artarilor",       "Arțarilor",      "tree"),
    ("platanilor",      "Platanilor",     "tree"),
    ("salcioarei",      "Sălcioarei",     "tree"),
    ("leandrului",      "Leandrului",     "tree"),
    ("aninilor",        "Aninilor",       "tree"),
    ("aninului",        "Aninului",       "tree"),
    ("cedrului",        "Cedrului",       "tree"),
    ("lamaiului",       "Lămâiului",      "tree"),
    ("migdalului",      "Migdalului",     "tree"),
    ("zarzarului",      "Zarzărului",     "tree"),
    ("merisorului",     "Merișorului",    "tree"),
    ("carpinis",        "Cărpiniș",       "forest"),
    ("zavoiului",       "Zăvoiului",      "forest"),
    ("zavoi",           "Zăvoi",          "forest"),
    ("dumbravii",       "Dumbrăvii",      "forest"),
    ("luminisului",     "Luminișului",    "meadow"),
    ("pajistei",        "Pajiștei",       "meadow"),  # duplicate guard handled by seen set
    ("poienii",         "Poienii",        "meadow"),
    ("runcului",        "Runcului",       "meadow"),
    # flowers — new entries + variants
    ("stanjeneilor",    "Stânjenelelor",  "flower"),
    ("stanjenelului",   "Stânjenelului",  "flower"),
    ("muscatei",        "Mușcatei",       "flower"),
    ("galbenelelor",    "Galbenelelor",   "flower"),
    ("tufanelelor",     "Tufănelelor",    "flower"),
    ("tufanului",       "Tufanului",      "flower"),
    ("daliilor",        "Daliilor",       "flower"),
    ("freziilor",       "Freziilor",      "flower"),
    ("magnoliilor",     "Magnoliilor",    "flower"),
    ("anemonei",        "Anemonei",       "flower"),
    ("azaleelor",       "Azaleelor",      "flower"),
    ("floarea soarelui","Floarea Soarelui","flower"),
    ("garofitelor",     "Garofițelor",    "flower"),
    ("margaritarelor",  "Mărgaritarelor", "flower"),
    ("viorele",         "Viorele",        "flower"),
    ("violetei",        "Violetei",       "flower"),
    ("ghiocei",         "Ghiocei",        "flower"),
    ("iris",            "Iris",           "flower"),
    ("toporasului",     "Toporașului",    "flower"),
    ("craitei",         "Crăiței",        "flower"),
    ("petalelor",       "Petalelor",      "flower"),
    ("lujerului",       "Lujerului",      "plant"),
    # plants
    ("iederei",         "Iederei",        "plant"),
    ("frunzei",         "Frunzei",        "plant"),
    ("frunzelor",       "Frunzelor",      "plant"),
    ("plantelor",       "Plantelor",      "plant"),
    ("trestiei",        "Trestiei",       "plant"),
    ("stufului",        "Stufului",       "plant"),
    ("lucernei",        "Lucernei",       "plant"),
    ("canepii",         "Cânepii",        "plant"),
    ("ferigii",         "Ferigii",        "plant"),
    ("cimbrului",       "Cimbrului",      "plant"),
    ("ghindei",         "Ghindei",        "plant"),
    ("fanului",         "Fânului",        "plant"),
    ("macrisului",      "Macrișului",     "plant"),
    ("lanului",         "Lanului",        "plant"),
    ("viei",            "Viei",           "plant"),
    ("mugurilor",       "Mugurilor",      "plant"),
    ("tarinei",         "Țarinei",        "plant"),
    ("tarina",          "Țarină",         "plant"),
    # fruits
    ("afinelor",        "Afinelor",       "fruit"),
    ("agriselor",       "Agrișelor",      "fruit"),
    ("murului",         "Murului",        "fruit"),
    # birds — new entries
    ("soimilor",        "Șoimilor",       "bird"),
    ("turturelelor",    "Turturelelor",   "bird"),
    ("albatrosului",    "Albatrosului",   "bird"),
    ("pelicanului",     "Pelicanului",    "bird"),
    ("paunului",        "Păunului",       "bird"),
    ("dropiei",         "Dropiei",        "bird"),
    ("lastunului",      "Lăstunului",     "bird"),
    ("porumbelului",    "Porumbelului",   "bird"),
    ("pescarus",        "Pescăruș",       "bird"),
    ("libelulei",       "Libelulei",      "animal"),
    ("licurici",        "Licurici",       "animal"),
    ("veveritei",       "Veveriței",      "animal"),
    ("leului",          "Leului",         "animal"),
    ("delfinului",      "Delfinului",     "animal"),
    ("mieilor",         "Mieilor",        "animal"),
    ("mioarelor",       "Mioarelor",      "animal"),
    ("fluturilor",      "Fluturilor",     "animal"),
    # water — new entries
    ("apelor",          "Apelor",         "water"),
    ("apei",            "Apei",           "water"),
    ("fantanei",        "Fântânei",       "water"),
    ("fantanele",       "Fântânele",      "water"),
    ("lacurilor",       "Lacurilor",      "water"),
    ("cascadei",        "Cascadei",       "water"),
    ("helesteului",     "Heleșteului",    "water"),
    ("sipotului",       "Șipotului",      "water"),
    ("putului",         "Puțului",        "water"),
    ("valcele",         "Vâlcele",        "water"),
    ("valcelei",        "Vâlcelei",       "water"),
    ("lunca",           "Lunca",          "meadow"),
    ("garlei",          "Gârlei",         "water"),  # dup guard
    # geography / terrain
    ("coastei",         "Coastei",        "geography"),
    ("nisipului",       "Nisipului",      "geography"),
    ("vailor",          "Văilor",         "geography"),
    ("pietris",         "Pietrișul",      "geography"),
    ("cornisei",        "Cornișei",       "geography"),
    ("dealul viilor",   "Dealul Viilor",  "geography"),
    ("dealul mare",     "Dealul Mare",    "geography"),
    ("valle mare",      "Valea Mare",     "geography"),
    ("valea seaca",     "Valea Seacă",    "geography"),
    ("izvorul rece",    "Izvorul Rece",   "water"),
    # seasons / sky
    ("iernii",          "Iernii",         "season"),
    ("cometei",         "Cometei",        "sky"),
    ("stelei",          "Stelei",         "sky"),
    ("luceafarul",      "Luceafărul",     "sky"),
    ("brizei",          "Brizei",         "weather"),
    ("zborului",        "Zborului",       "weather"),
]

# (core_name_norm, full_name, gender, birth, death, era, profession, nat, qid)
PERSONS = [
    ("nicolae grigorescu",    "Nicolae Grigorescu",           "M", 1838, 1907, "premodern", "painter",     "RO", "Q330815"),
    ("horea",                 "Horia",                        "M", 1730, 1785, "premodern", "revolutionary","RO", None),
    ("constantin dobrogeanu gherea","Constantin Dobrogeanu-Gherea","M",1855,1920,"premodern","politician","RO", "Q647428"),
    ("dobrogeanu gherea",     "Constantin Dobrogeanu-Gherea", "M", 1855, 1920, "premodern", "politician",  "RO", "Q647428"),
    ("emil racovita",         "Emil Racoviță",                "M", 1868, 1947, "premodern", "scientist",   "RO", "Q524488"),
    ("ecaterina varga",       "Ecaterina Varga",              "F", 1821, 1852, "1848",      "revolutionary","RO", None),
    ("mircea voda",           "Mircea cel Bătrân",            "M", 1355, 1418, "medieval",  "voievod",     "RO", "Q208494"),
    ("tepes voda",            "Vlad Țepeș",                   "M", 1428, 1477, "medieval",  "voievod",     "RO", "Q44611"),
    ("panait cerna",          "Panait Cerna",                 "M", 1881, 1913, "premodern", "poet",        "RO", None),
    ("calistrat hogas",       "Calistrat Hogaș",              "M", 1847, 1917, "premodern", "writer",      "RO", None),
    ("ionel teodoreanu",      "Ionel Teodoreanu",             "M", 1897, 1954, "interwar",  "writer",      "RO", None),
    ("timotei cipariu",       "Timotei Cipariu",              "M", 1805, 1887, "premodern", "historian",   "RO", "Q647404"),
    ("ion c. bratianu",       "Ion C. Brătianu",              "M", 1821, 1891, "premodern", "politician",  "RO", "Q647429"),
    ("i. c. bratianu",        "Ion C. Brătianu",              "M", 1821, 1891, "premodern", "politician",  "RO", "Q647429"),
    ("vasile conta",          "Vasile Conta",                 "M", 1845, 1882, "premodern", "philosopher", "RO", "Q2524023"),
    ("zaharia stancu",        "Zaharia Stancu",               "M", 1902, 1974, "communist", "writer",      "RO", None),
    ("aron pumnul",           "Aron Pumnul",                  "M", 1818, 1866, "premodern", "educator",    "RO", None),
    ("ion agarbiceanu",       "Ion Agârbiceanu",              "M", 1882, 1963, "interwar",  "writer",      "RO", None),
    ("ion andreescu",         "Ion Andreescu",                "M", 1850, 1882, "premodern", "painter",     "RO", "Q1398494"),
    ("ion ghica",             "Ion Ghica",                    "M", 1816, 1897, "premodern", "politician",  "RO", "Q647476"),
    ("lazar gheorghe",        "Gheorghe Lazăr",               "M", 1779, 1823, "premodern", "educator",    "RO", "Q952971"),
    ("mihai bravu",           "Mihai Viteazul",               "M", 1558, 1601, "medieval",  "voievod",     "RO", "Q156605"),
    ("baba novac",            "Baba Novac",                   "M", 1530, 1601, "medieval",  "military",    "RO", None),
    ("duiliu zamfirescu",     "Duiliu Zamfirescu",            "M", 1858, 1922, "premodern", "writer",      "RO", "Q647380"),
    ("bartok bela",           "Bartók Béla",                  "M", 1881, 1945, "interwar",  "composer",    "HU", "Q83359"),
    ("arany janos",           "Arany János",                  "M", 1817, 1882, "premodern", "poet",        "HU", "Q152690"),
    ("jokai mor",             "Jókai Mór",                    "M", 1825, 1904, "premodern", "writer",      "HU", "Q168717"),
    ("jozsef attila",         "József Attila",                "M", 1905, 1937, "interwar",  "poet",        "HU", "Q130786"),
    ("penes curcanul",        "Peneș Curcanul",               "M", 1840, 1900, "premodern", "military",    "RO", None),
    ("g-ral ion dragalina",   "Ion Drăgălina",                "M", 1860, 1916, "premodern", "military",    "RO", None),
    ("miron cristea",         "Patriarh Miron Cristea",       "M", 1868, 1938, "interwar",  "clergy",      "RO", "Q522024"),
    ("octav bancila",         "Octav Băncilă",                "M", 1872, 1944, "interwar",  "painter",     "RO", None),
    ("vasile carlova",        "Vasile Cârlova",               "M", 1809, 1831, "premodern", "poet",        "RO", None),
    ("ana aslan",             "Ana Aslan",                    "F", 1897, 1988, "communist", "scientist",   "RO", "Q437004"),
    ("badea cartan",          "Badea Cârțan",                 "M", 1849, 1911, "premodern", "educator",    "RO", None),
    ("Ioan budai-deleanu",    "Ioan Budai-Deleanu",           "M", 1760, 1820, "premodern", "writer",      "RO", "Q647402"),
    ("ion roata",             "Ion Roată",                    "M", 1806, 1876, "1848",      "revolutionary","RO", None),
    ("mos ion roata",         "Moș Ion Roată",                "M", 1806, 1876, "1848",      "revolutionary","RO", None),
    ("iosif vulcan",          "Iosif Vulcan",                 "M", 1841, 1907, "premodern", "writer",      "RO", "Q647484"),
    ("vulcan",                "Samuil Vulcan",                "M", 1758, 1839, "premodern", "clergy",      "RO", None),
    ("panait istrati",        "Panait Istrati",               "M", 1884, 1935, "interwar",  "writer",      "RO", "Q214952"),
    ("tudor vianu",           "Tudor Vianu",                  "M", 1897, 1964, "interwar",  "writer",      "RO", "Q8273058"),
    ("adrian paunescu",       "Adrian Păunescu",              "M", 1943, 2010, "communist", "poet",        "RO", "Q381161"),
    ("eugen lovinescu",       "Eugen Lovinescu",              "M", 1881, 1943, "interwar",  "writer",      "RO", "Q647492"),
    ("a. i. cuza",            "Alexandru Ioan Cuza",          "M", 1820, 1873, "premodern", "politician",  "RO", "Q208518"),
    ("elena cuza",            "Elena Cuza",                   "F", 1825, 1909, "premodern", "royalty",     "RO", None),
    ("elena doamna",          "Elena Cuza",                   "F", 1825, 1909, "premodern", "royalty",     "RO", None),
    ("doamna stanca",         "Doamna Stanca",                "F", 1571, 1603, "medieval",  "royalty",     "RO", None),
    ("cezar petrescu",        "Cezar Petrescu",               "M", 1892, 1961, "interwar",  "writer",      "RO", None),
    ("eremia grigorescu",     "Eremia Grigorescu",            "M", 1863, 1919, "premodern", "military",    "RO", "Q1372003"),
    ("ferdinand i",           "Regele Ferdinand I",           "M", 1865, 1927, "interwar",  "royalty",     "RO", "Q159014"),
    ("marton aron",           "Márton Áron",                  "M", 1896, 1980, "communist", "clergy",      "RO", "Q311556"),
    ("gen. david praporgescu","David Praporgescu",            "M", 1866, 1916, "premodern", "military",    "RO", None),
    ("geo bogza",             "Geo Bogza",                    "M", 1908, 1993, "communist", "writer",      "RO", None),
    ("ion barbu",             "Ion Barbu",                    "M", 1895, 1961, "interwar",  "poet",        "RO", "Q647478"),
    ("ion ionescu de la brad","Ion Ionescu de la Brad",       "M", 1818, 1891, "premodern", "scientist",   "RO", None),
    ("otilia cazimir",        "Otilia Cazimir",               "F", 1894, 1967, "interwar",  "poet",        "RO", None),
    ("petrache poenaru",      "Petrache Poenaru",             "M", 1799, 1875, "premodern", "engineer",    "RO", "Q647536"),
    ("petre tutea",           "Petre Țuțea",                  "M", 1902, 1991, "communist", "philosopher", "RO", None),
    ("g-ral gheorghe magheru","Gheorghe Magheru",             "M", 1804, 1880, "1848",      "military",    "RO", "Q647447"),
    ("gabor aron",            "Gábor Áron",                   "M", 1814, 1849, "1848",      "military",    "HU", "Q240299"),
    ("kossuth lajos",         "Kossuth Lajos",                "M", 1802, 1894, "premodern", "politician",  "HU", "Q48592"),
    ("bethlen gabor",         "Bethlen Gábor",                "M", 1580, 1629, "medieval",  "royalty",     "HU", "Q125375"),
    ("budai nagy antal",      "Budai Nagy Antal",             "M", None, 1437, "medieval",  "revolutionary","HU", None),
    ("grigore antipa",        "Grigore Antipa",               "M", 1867, 1944, "interwar",  "scientist",   "RO", "Q647456"),
    ("dinicu golescu",        "Dinicu Golescu",               "M", 1777, 1830, "premodern", "writer",      "RO", "Q647434"),
    ("dinu lipatti",          "Dinu Lipatti",                 "M", 1917, 1950, "interwar",  "musician",    "RO", "Q355898"),
    ("approdul purice",       "Aprodul Purice",               "M", None, None, "medieval",  "military",    "RO", None),
    ("banu maracine",         "Banu Mărăcine",                "M", None, None, "medieval",  "legendary",   "RO", None),
    ("radu negru",            "Radu Negru",                   "M", None, 1290, "medieval",  "voievod",     "RO", None),
    ("mircea cel mare",       "Mircea cel Bătrân",            "M", 1355, 1418, "medieval",  "voievod",     "RO", "Q208494"),
    ("stirbei voda",          "Barbu Știrbei",                "M", 1799, 1869, "premodern", "voievod",     "RO", None),
    ("stefan luchian",        "Ștefan Luchian",               "M", 1868, 1916, "premodern", "painter",     "RO", "Q330905"),
    ("ion vidu",              "Ion Vidu",                     "M", 1863, 1931, "premodern", "composer",    "RO", None),
    ("emil garleanu",         "Emil Gârleanu",                "M", 1878, 1914, "premodern", "writer",      "RO", None),
    ("popa sapca",            "Popa Șapcă",                   "M", 1810, 1860, "1848",      "clergy",      "RO", None),
    ("alexandru sahia",       "Alexandru Sahia",              "M", 1908, 1937, "communist", "writer",      "RO", None),
    ("nicolae tonitza",       "Nicolae Tonitza",              "M", 1886, 1940, "interwar",  "painter",     "RO", "Q1028044"),
    ("cezar bolliac",         "Cezar Bolliac",                "M", 1813, 1881, "1848",      "poet",        "RO", None),
    ("aron pumnul",           "Aron Pumnul",                  "M", 1818, 1866, "premodern", "educator",    "RO", None),
    ("ion mihalache",         "Ion Mihalache",                "M", 1882, 1963, "interwar",  "politician",  "RO", None),
    ("ion nistor",            "Ion Nistor",                   "M", 1876, 1962, "interwar",  "historian",   "RO", None),
    ("timisoarei",            None, None, None, None, None, None, None, None),  # skip — place not person
    ("vasile conta",          "Vasile Conta",                 "M", 1845, 1882, "premodern", "philosopher", "RO", None),
    ("corneliu coposu",       "Corneliu Coposu",              "M", 1914, 1995, "communist", "politician",  "RO", "Q528773"),
    ("horia,closca si crisan","Horia, Cloșca și Crișan",     "collective", None, 1785, "premodern", "revolutionary", "RO", None),
    ("fratii buzesti",        "Frații Buzești",               "collective", None, None, "medieval", "military", "RO", None),
    ("constantin noica",      "Constantin Noica",             "M", 1909, 1987, "communist", "philosopher", "RO", "Q336614"),
    ("alecu russo",           "Alecu Russo",                  "M", 1819, 1859, "1848",      "writer",      "RO", None),
    ("cronicar ion neculce",  "Ion Neculce",                  "M", 1672, 1745, "medieval",  "writer",      "RO", "Q647489"),
    ("alexandru macedonski",  "Alexandru Macedonski",         "M", 1854, 1920, "premodern", "poet",        "RO", "Q647364"),
    ("iosif vulcan",          "Iosif Vulcan",                 "M", 1841, 1907, "premodern", "writer",      "RO", "Q647484"),
    ("timotei cipariu",       "Timotei Cipariu",              "M", 1805, 1887, "premodern", "historian",   "RO", "Q647404"),
    ("bartok bela",           "Bartók Béla",                  "M", 1881, 1945, "interwar",  "composer",    "HU", "Q83359"),
    ("octav bancila",         "Octav Băncilă",                "M", 1872, 1944, "interwar",  "painter",     "RO", None),
    ("calistrat hogas",       "Calistrat Hogaș",              "M", 1847, 1917, "premodern", "writer",      "RO", None),
    ("miorita",               None, None, None, None, None, None, None, None),  # skip — folk ballad, not a person
    ("i.l. caragiale",        "Ion Luca Caragiale",           "M", 1852, 1912, "premodern", "writer",      "RO", "Q217022"),
    ("petre tutea",           "Petre Țuțea",                  "M", 1902, 1991, "communist", "philosopher", "RO", None),
    ("eugen lovinescu",       "Eugen Lovinescu",              "M", 1881, 1943, "interwar",  "writer",      "RO", None),
    ("aron pumnul",           "Aron Pumnul",                  "M", 1818, 1866, "premodern", "educator",    "RO", None),
    ("duiliu zamfirescu",     "Duiliu Zamfirescu",            "M", 1858, 1922, "premodern", "writer",      "RO", None),
    ("geo bogza",             "Geo Bogza",                    "M", 1908, 1993, "communist", "writer",      "RO", None),
    ("otilia cazimir",        "Otilia Cazimir",               "F", 1894, 1967, "interwar",  "poet",        "RO", None),
    ("grigore alexandrescu",  "Grigore Alexandrescu",         "M", 1810, 1885, "premodern", "writer",      "RO", None),
    ("petre tutea",           "Petre Țuțea",                  "M", 1902, 1991, "communist", "philosopher", "RO", None),
    ("adrian paunescu",       "Adrian Păunescu",              "M", 1943, 2010, "communist", "poet",        "RO", "Q381161"),
    ("gheorghe baritiu",      "Gheorghe Barițiu",             "M", 1812, 1893, "premodern", "historian",   "RO", None),
    ("popes sapca",           "Popa Șapcă",                   "M", 1810, 1860, "1848",      "clergy",      "RO", None),
    ("gheorghe asachi",       "Gheorghe Asachi",              "M", 1788, 1869, "premodern", "writer",      "RO", None),
    ("veronica micle",        "Veronica Micle",               "F", 1850, 1889, "premodern", "poet",        "RO", "Q561702"),
    ("ion minulescu",         "Ion Minulescu",                "M", 1881, 1944, "interwar",  "poet",        "RO", None),
    ("vasile goldis",         "Vasile Goldiș",                "M", 1862, 1934, "interwar",  "politician",  "RO", None),
    ("george calinescu",      "George Călinescu",             "M", 1899, 1965, "interwar",  "writer",      "RO", None),
    ("marin sorescu",         "Marin Sorescu",                "M", 1936, 1996, "communist", "writer",      "RO", None),
    ("barbu stefanescu delavrancea","Barbu Ștefănescu Delavrancea","M",1858,1918,"premodern","writer","RO",None),
    ("barbu lautaru",         "Barbu Lăutaru",                "M", 1780, 1858, "premodern", "musician",    "RO", None),
    ("grigore ureche",        "Grigore Ureche",               "M", 1590, 1647, "medieval",  "writer",      "RO", None),
    ("grigore alexandrescu",  "Grigore Alexandrescu",         "M", 1810, 1885, "premodern", "writer",      "RO", None),
    ("penes curcanul",        "Peneș Curcanul",               "M", 1840, 1900, "premodern", "military",    "RO", None),
    ("Ioan budai-deleanu",    "Ioan Budai-Deleanu",           "M", 1760, 1820, "premodern", "writer",      "RO", None),
    ("gen. david praporgescu","David Praporgescu",            "M", 1866, 1916, "premodern", "military",    "RO", None),
    ("miron costin",          "Miron Costin",                 "M", 1633, 1691, "medieval",  "writer",      "RO", None),
    ("ion heliade radulescu", "Ion Heliade Rădulescu",        "M", 1802, 1872, "premodern", "writer",      "RO", None),
    ("petru maior",           "Petru Maior",                  "M", 1760, 1821, "premodern", "historian",   "RO", None),
    ("gheorghe sincai",       "Gheorghe Șincai",              "M", 1754, 1816, "premodern", "historian",   "RO", None),
    ("andrei saguna",         "Andrei Șaguna",                "M", 1809, 1873, "premodern", "clergy",      "RO", None),
    ("bogdan petriceicu hasdeu","Bogdan Petriceicu Hașdeu",   "M", 1838, 1907, "premodern", "writer",      "RO", None),
    ("ovidiu",                "Publius Ovidius Naso",         "M", -43,   17,  "ancient",   "writer",      None, "Q7198"),
    ("vasile lucaciu",        "Vasile Lucaciu",               "M", 1852, 1922, "premodern", "clergy",      "RO", None),
    ("stefan octavian iosif", "Ștefan Octavian Iosif",        "M", 1875, 1913, "premodern", "poet",        "RO", None),
    ("corneliu coposu",       "Corneliu Coposu",              "M", 1914, 1995, "communist", "politician",  "RO", None),
    ("emil cioran",           "Emil Cioran",                  "M", 1911, 1995, "interwar",  "philosopher", "RO", None),
    ("mircea eliade",         "Mircea Eliade",                "M", 1907, 1986, "interwar",  "philosopher", "RO", None),
    ("camil petrescu",        "Camil Petrescu",               "M", 1894, 1957, "interwar",  "writer",      "RO", None),
    ("ion neculce",           "Ion Neculce",                  "M", 1672, 1745, "medieval",  "writer",      "RO", None),
    ("alecu russo",           "Alecu Russo",                  "M", 1819, 1859, "1848",      "writer",      "RO", None),
    ("spiru haret",           "Spiru Haret",                  "M", 1851, 1912, "premodern", "educator",    "RO", None),
    ("liviu rebreanu",        "Liviu Rebreanu",               "M", 1885, 1944, "interwar",  "writer",      "RO", None),
]

# (core_name_norm, category, subcategory)
CATEGORIES = [
    # religious
    ("cetatii",         "institutional",  "fortress"),
    ("manastirii",      "religious",      "monastery"),
    ("schitului",       "religious",      "hermitage"),
    ("troitei",         "religious",      "wayside_shrine"),
    ("crucii",          "religious",      "cross"),
    ("capelei",         "religious",      "chapel"),
    ("parohiei",        "religious",      "parish"),
    ("anvierii",        "religious",      "easter"),
    ("buna vestire",    "religious",      "annunciation"),
    ("biserca veche",   "religious",      "church"),
    # ideological
    ("dezrobirii",      "ideological",    "emancipation"),
    ("eliberarii",      "ideological",    "liberation"),
    ("solidaritatii",   "ideological",    "solidarity"),
    ("muncitorilor",    "ideological",    "workers"),
    ("egalitatii",      "ideological",    "equality"),
    ("fratiei",         "ideological",    "brotherhood"),
    ("fraternitatii",   "ideological",    "fraternity"),
    ("22 decembrie 1989","ideological",   "national_day"),
    ("patriei",         "ideological",    "homeland"),
    ("scanteii",        "ideological",    "communist_press"),
    ("triumfului",      "ideological",    "triumph"),
    ("cooperatiei",     "ideological",    "cooperative"),
    # abstract
    ("mioritei",        "abstract",       "folk_culture"),
    ("miorita",         "abstract",       "folk_culture"),
    ("hotarului",       "abstract",       "boundary"),
    ("ecoului",         "abstract",       "echo"),
    ("muzicii",         "abstract",       "music"),
    ("lirei",           "abstract",       "music"),
    ("muzelor",         "abstract",       "music"),
    ("rapsodiei",       "abstract",       "music"),
    ("veche",           "abstract",       "old"),
    ("verde",           "abstract",       "green"),
    ("anfundata",       "abstract",       "cul_de_sac"),
    ("fundaturii",      "abstract",       "cul_de_sac"),
    ("labirint",        "abstract",       "labyrinth"),
    ("diminetii",       "abstract",       "morning"),
    ("bucuriei",        "abstract",       "joy"),
    ("fericirii",       "abstract",       "happiness"),
    ("veseliei",        "abstract",       "joy"),
    ("timpului",        "abstract",       "time"),
    ("stiintei",        "abstract",       "science"),
    ("zborului",        "abstract",       "flight"),
    ("urcusului",       "abstract",       "ascent"),
    ("rubinului",       "abstract",       "jewel"),
    ("perlei",          "abstract",       "jewel"),
    ("rotunda",         "abstract",       "round"),
    ("stramba",         "abstract",       "crooked"),
    ("nationala",       "abstract",       "national"),
    ("centrala",        "abstract",       "central"),
    # mythology
    ("marte",           "mythology",      "roman_deity"),
    ("minerva",         "mythology",      "roman_deity"),
    ("orion",           "mythology",      "mythology"),
    ("sirenei",         "mythology",      "mythology"),
    ("sabinelor",       "mythology",      "roman_history"),
    ("romulus",         "mythology",      "roman_history"),
    # institutional
    ("monumentului",    "institutional",  "monument"),
    ("castelului",      "institutional",  "castle"),
    ("taberei",         "institutional",  "camp"),
    ("arenei",          "institutional",  "arena"),
    ("bancii",          "institutional",  "bank"),
    ("academiei",       "institutional",  "academy"),
    ("artelor",         "institutional",  "arts"),
    ("artelor",         "institutional",  "arts"),
    ("liceului",        "institutional",  "school"),
    ("policlinicii",    "institutional",  "polyclinic"),
    ("farmaciei",       "institutional",  "pharmacy"),
    ("aeroportului",    "institutional",  "airport"),
    ("baii",            "institutional",  "spa_baths"),
    ("bailor",          "institutional",  "spa_baths"),
    ("bazinului",       "institutional",  "pool"),
    ("complexului",     "institutional",  "complex"),
    ("sanatatii",       "institutional",  "health"),
    ("politiei",        "institutional",  "police"),
    ("portului",        "institutional",  "port"),
    ("turnului",        "institutional",  "tower"),
    ("asociatiei",      "institutional",  "association"),
    ("conacului",       "institutional",  "manor"),
    ("cazarmii",        "institutional",  "barracks"),
    ("depoului",        "institutional",  "depot"),
    ("c.f.r.",          "institutional",  "railway"),
    ("locomotivei",     "institutional",  "railway"),
    ("triajului",       "institutional",  "railway"),
    ("cabanei",         "institutional",  "cabin"),
    ("stadion",         "institutional",  "stadium"),
    ("scoala veche",    "institutional",  "school"),
    ("foișor",          "institutional",  "gazebo"),
    ("foisorului",      "institutional",  "gazebo"),
    ("chimiei",         "institutional",  "science"),
    ("metalurgiei",     "trade",          "metallurgy"),
    ("zootehniei",      "trade",          "farming"),
    ("avicola",         "trade",          "poultry"),
    ("cerealelor",      "trade",          "cereals"),
    ("fuiorului",       "trade",          "textile"),
    ("lutariei",        "occupational",   "musicians"),
    ("cramei",          "trade",          "winery"),
    ("vinului",         "trade",          "wine"),
    ("petrolului",      "trade",          "petroleum"),
    ("sondelor",        "trade",          "oil_wells"),
    ("minei",           "trade",          "mine"),
    ("minerului",       "occupational",   "miner"),
    ("petrolistilor",   "occupational",   "oil_workers"),
    ("ceferistilor",    "occupational",   "railway_workers"),
    ("feroviarilor",    "occupational",   "railway_workers"),
    ("mecanizatorilor", "occupational",   "operators"),
    ("tractoristilor",  "occupational",   "operators"),
    ("dogarilor",       "trade",          "barrel_makers"),
    ("dogarului",       "trade",          "barrel_maker"),
    ("cojocarilor",     "trade",          "furriers"),
    ("croitorului",     "occupational",   "tailor"),
    ("tamplarilor",     "occupational",   "carpenters"),
    ("zidarilor",       "occupational",   "masons"),
    ("fierarului",      "trade",          "blacksmith"),
    ("fierariei",       "trade",          "blacksmith_shop"),
    ("ciobanului",      "occupational",   "shepherd"),
    ("pastorului",      "occupational",   "shepherd"),
    ("morarului",       "occupational",   "miller"),
    ("morarilor",       "occupational",   "millers"),
    ("mestesugarilor",  "occupational",   "craftsmen"),
    ("postasului",      "occupational",   "postal_worker"),
    ("agriculturii",    "institutional",  "agriculture"),
    ("agriculturii",    "institutional",  "agriculture"),
    ("fermierilor",     "occupational",   "farmers"),
    ("fermierului",     "occupational",   "farmer"),
    ("agricultorului",  "occupational",   "farmer"),
    ("apicultorilor",   "occupational",   "beekeepers"),
    ("stupinei",        "trade",          "apiary"),
    ("pescariei",       "trade",          "fishmonger"),
    ("gradinarilor",    "occupational",   "gardeners"),
    ("padurarilor",     "occupational",   "foresters"),
    ("padurarului",     "occupational",   "forester"),
    ("sportivilor",     "occupational",   "athletes"),
    ("pictorului",      "occupational",   "painter"),
    ("poetului",        "occupational",   "poet"),
    ("muzicantilor",    "occupational",   "musicians"),
    ("gospodarilor",    "occupational",   "householders"),
    ("caramidariei",    "trade",          "brickyard"),
    ("caramidari",      "trade",          "brickyard"),
    ("atelierului",     "trade",          "workshop"),
    ("granicerilor",    "commemorative",  "border_guards"),
    ("armatei",         "commemorative",  "military"),
    ("arcasilor",       "commemorative",  "archers"),
    ("haiducilor",      "commemorative",  "outlaws"),
    ("haiducului",      "commemorative",  "outlaw"),
    ("partizanilor",    "commemorative",  "partisans"),
    ("romanilor",       "commemorative",  "romans"),
    ("dacilor",         "commemorative",  "dacians"),
    ("industriilor",    "trade",          "industry"),
    ("plantatiei",      "trade",          "plantation"),
    ("pietii",          "trade",          "market"),
    ("pietei",          "trade",          "market"),
    ("obor",            "trade",          "market"),
    ("morilor",         "trade",          "mill"),
    ("barierei",        "infrastructure", "barrier"),
    ("puntii",          "infrastructure", "bridge"),
    ("releului",        "infrastructure", "relay"),
    ("transformatorului","infrastructure","electrical"),
    ("depozitelor",     "trade",          "warehouse"),
    ("silozului",       "trade",          "silo"),
    ("ogorului",        "trade",          "agriculture"),
    ("serelor",         "trade",          "greenhouse"),
    ("serei",           "trade",          "greenhouse"),
    ("pepinierei",      "trade",          "nursery"),
    ("balastierei",     "trade",          "quarry"),
    ("potcoavei",       "trade",          "blacksmith"),
    ("ograzii",         "abstract",       "courtyard"),
    ("movilei",         "abstract",       "mound"),
    ("razoare",         "abstract",       "furrow"),
    ("recunostintei",   "abstract",       "gratitude"),
    ("avantului",       "abstract",       "impetus"),
    ("belvedere",       "abstract",       "scenic_view"),
    ("orizont",         "abstract",       "horizon"),
    ("flacara",         "abstract",       "flame"),
    ("armoniei",        "abstract",       "harmony"),
    ("dezrobirii",      "ideological",    "emancipation"),
    ("linia mare",      "abstract",       "main_line"),
    ("doinei",          "abstract",       "folk_music"),
    ("muzicii",         "abstract",       "music"),
]

# (core_name_norm, place_name, place_type, country)
PLACES = [
    # rivers
    ("dambovitei",     "Dâmbovița",       "river",         "RO"),
    ("dambovita",      "Dâmbovița",       "river",         "RO"),
    ("prahovei",       "Prahova",         "river",         "RO"),
    ("sucevei",        "Suceava",         "river",         "RO"),
    ("oltetului",      "Oltețul",         "river",         "RO"),
    ("timisului",      "Timiș",           "river",         "RO"),
    ("trotusului",     "Trotuș",          "river",         "RO"),
    ("trotus",         "Trotuș",          "river",         "RO"),
    ("tisei",          "Tisa",            "river",         None),
    ("somes",          "Someș",           "river",         "RO"),
    ("arges",          "Argeș",           "river",         "RO"),
    ("buzaului",       "Buzău",           "river",         "RO"),
    ("bega",           "Bega",            "river",         "RO"),
    ("bistrita",       "Bistrița",        "river",         "RO"),
    ("cibinului",      "Cibin",           "river",         "RO"),
    ("tarnavei",       "Târnava",         "river",         "RO"),
    ("timis",          "Timiș",           "river",         "RO"),
    ("dunarea",        "Dunărea",         "river",         "RO"),
    ("ialomitei",      "Ialomița",        "river",         "RO"),
    ("putnei",         "Putna",           "river",         "RO"),
    ("oasului",        "Oaș",             "region",        "RO"),
    ("brailei",        "Brăila",          "ro_city",       "RO"),
    # mountains / peaks
    ("ceahlau",        "Ceahlău",         "mountain",      "RO"),
    ("retezat",        "Retezat",         "mountain",      "RO"),
    ("negoiu",         "Negoiu",          "mountain_peak", "RO"),
    ("ciucas",         "Ciucaș",          "mountain",      "RO"),
    ("clabucet",       "Clăbucet",        "mountain",      "RO"),
    ("caliman",        "Căliman",         "mountain",      "RO"),
    ("fagarasului",    "Munții Făgăraș",  "mountain",      "RO"),
    ("rarau",          "Rarău",           "mountain",      "RO"),
    ("vladeasa",       "Vlădeasa",        "mountain_peak", "RO"),
    ("semenic",        "Semenic",         "mountain",      "RO"),
    ("parang",         "Parâng",          "mountain",      "RO"),
    ("piatra craiului","Piatra Craiului",  "mountain",      "RO"),
    # regions
    ("crisana",        "Crișana",         "region",        "RO"),
    ("baraganului",    "Bărăgan",         "region",        "RO"),
    ("vrancei",        "Vrancea",         "region",        "RO"),
    ("bihorului",      "Bihor",           "region",        "RO"),
    ("basarabiei",     "Basarabia",       "region",        None),
    ("basarabia",      "Basarabia",       "region",        None),
    ("dobrogei",       "Dobrogea",        "region",        "RO"),
    ("munteniei",      "Muntenia",        "region",        "RO"),
    ("banatului",      "Banat",           "region",        "RO"),
    ("banat",          "Banat",           "region",        "RO"),
    ("ardealului",     "Ardeal",          "region",        "RO"),
    ("transistilvaniei","Transilvania",   "region",        "RO"),
    ("bucovina",       "Bucovina",        "region",        "RO"),
    ("zarandului",     "Zarand",          "region",        "RO"),
    # cities / towns
    ("timisoarei",     "Timișoara",       "ro_city",       "RO"),
    ("clujului",       "Cluj-Napoca",     "ro_city",       "RO"),
    ("cluj",           "Cluj-Napoca",     "ro_city",       "RO"),
    ("bistrita",       "Bistrița",        "ro_city",       "RO"),
    ("constantei",     "Constanța",       "ro_city",       "RO"),
    ("galati",         "Galați",          "ro_city",       "RO"),
    ("giurgiului",     "Giurgiu",         "ro_city",       "RO"),
    ("brasovului",     "Brașov",          "ro_city",       "RO"),
    ("brasov",         "Brașov",          "ro_city",       "RO"),
    ("aradului",       "Arad",            "ro_city",       "RO"),
    ("campeni",        "Câmpeni",         "ro_city",       "RO"),
    ("dornei",         "Vatra Dornei",    "ro_city",       "RO"),
    ("sucevei",        "Suceava",         "ro_city",       "RO"),
    ("predeal",        "Predeal",         "resort",        "RO"),
    ("sinaia",         "Sinaia",          "resort",        "RO"),
    ("olimp",          "Olimp",           "resort",        "RO"),
    ("azuga",          "Azuga",           "resort",        "RO"),
    ("lupeni",         "Lupeni",          "ro_city",       "RO"),
    ("rosiori",        "Roșiori de Vede", "ro_city",       "RO"),
    ("tomis",          "Tomis",           "ancient_city",  "RO"),
    ("sarmisegetuza",  "Sarmizegetusa",   "ancient_city",  "RO"),
    ("tismana",        "Tismana",         "ro_village",    "RO"),
    ("mircesti",       "Mircești",        "ro_village",    "RO"),
    ("deltei",         "Delta Dunării",   "region",        "RO"),
    ("cozia",          "Cozia",           "ro_monastery",  "RO"),
    ("putna",          "Putna",           "ro_monastery",  "RO"),
    ("fagaras",        "Făgăraș",         "ro_city",       "RO"),
    ("dacia",          "Dacia",           "ancient_region","RO"),
    ("daciei",         "Dacia",           "ancient_region","RO"),
    ("scarisoara",     "Scărișoara",      "ro_village",    "RO"),
    # foreign cities
    ("londra",         "Londra",          "city",          "GB"),
    ("madrid",         "Madrid",          "city",          "ES"),
    ("atena",          "Atena",           "city",          "GR"),
    ("roma",           "Roma",            "city",          "IT"),
    ("viena",          "Viena",           "city",          "AT"),
    ("berlin",         "Berlin",          "city",          "DE"),
    ("sofia",          "Sofia",           "city",          "BG"),
    ("praga",          "Praga",           "city",          "CZ"),
    ("lisabona",       "Lisabona",        "city",          "PT"),
    ("vidin",          "Vidin",           "battle_site",   "BG"),
]


# ── CSV GENERATION ─────────────────────────────────────────────────────────
HEADER = [
    "core_name_norm", "freq", "judete_n", "uats_n", "sample_name", "judete_list",
    "table",
    "full_name", "gender", "birth_year", "death_year", "era", "profession",
    "nationality", "wikidata_qid",
    "term", "nature_type",
    "category", "subcategory",
    "place_name", "place_type", "country",
    "notes",
]

def row(**kw):
    r = {h: "" for h in HEADER}
    r.update(kw)
    return r

rows = []
seen = {t: set() for t in ("nature_terms", "persons", "name_categories", "place_refs")}

for (cnorm, term, ntype) in NATURE:
    if cnorm in seen["nature_terms"]:
        continue
    seen["nature_terms"].add(cnorm)
    rows.append(row(core_name_norm=cnorm, table="nature_terms",
                    term=term, nature_type=ntype))

for t in PERSONS:
    cnorm = t[0]
    full_name = t[1]
    if full_name is None:  # explicit skip
        continue
    if cnorm in seen["persons"]:
        continue
    seen["persons"].add(cnorm)
    cnorm, full, gender, birth, death, era, prof, nat, qid = t
    rows.append(row(
        core_name_norm=cnorm, table="persons",
        full_name=full, gender=gender or "",
        birth_year="" if birth is None else birth,
        death_year="" if death is None else death,
        era=era or "", profession=prof or "",
        nationality=nat or "", wikidata_qid=qid or "",
    ))

for t in CATEGORIES:
    cnorm, cat, sub = t
    if cnorm in seen["name_categories"]:
        continue
    seen["name_categories"].add(cnorm)
    rows.append(row(core_name_norm=cnorm, table="name_categories",
                    category=cat, subcategory=sub))

for t in PLACES:
    cnorm, pname, ptype, country = t
    if cnorm in seen["place_refs"]:
        continue
    seen["place_refs"].add(cnorm)
    rows.append(row(core_name_norm=cnorm, table="place_refs",
                    place_name=pname, place_type=ptype, country=country or ""))

OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=HEADER)
    w.writeheader()
    w.writerows(rows)

print(f"Generated {len(rows)} rows → {OUT}")
print(f"  nature_terms   : {sum(1 for r in rows if r['table']=='nature_terms')}")
print(f"  persons        : {sum(1 for r in rows if r['table']=='persons')}")
print(f"  name_categories: {sum(1 for r in rows if r['table']=='name_categories')}")
print(f"  place_refs     : {sum(1 for r in rows if r['table']=='place_refs')}")

if "--dry-run" not in sys.argv:
    result = subprocess.run(
        ["python3", "tools/import_csv.py", str(OUT)],
        capture_output=True, text=True
    )
    print(result.stdout)
    if result.returncode != 0:
        print("ERRORS:", result.stderr)
        sys.exit(1)
